export const MachineEventTypes = {
  DIGIT_CLICKED: 'DIGIT_CLICKED',
  OPERATOR_CLICKED: 'OPERATOR_CLICKED',
  PERCENT_SIGN_CLICKED: 'PERCENT_SIGN_CLICKED',
  DECIMAL_POINT_CLICKED: 'DECIMAL_POINT_CLICKED',
  CLEAR_BUTTON_CLICKED: 'CLEAR_BUTTON_CLICKED',
  EQUAL_SIGN_CLICKED: 'EQUAL_SIGN_CLICKED',
  OK_BUTTON_CLICKED: 'OK_BUTTON_CLICKED',
  RESET_CLICKED: 'RESET_CLICKED',
  PARENTHESES_CLICKED: 'PARENTHESES_CLICKED',
} as const;
